// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuwPgpLkcS03HBKbSSWG-SRUQ7AzNpu8M',
    appId: '1:731342575492:web:288f431f091efbed9aefd1',
    messagingSenderId: '731342575492',
    projectId: 'mailsender-3ca8b',
    authDomain: 'mailsender-3ca8b.firebaseapp.com',
    storageBucket: 'mailsender-3ca8b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBADp8vLpo7t8NTcCh9cQnjQznbZBsC8AU',
    appId: '1:731342575492:android:665efd141108b3149aefd1',
    messagingSenderId: '731342575492',
    projectId: 'mailsender-3ca8b',
    storageBucket: 'mailsender-3ca8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjlaxuHdTZ5m_wxBfb8BSQodSOEaKrag4',
    appId: '1:731342575492:ios:cd5eb51b625c43079aefd1',
    messagingSenderId: '731342575492',
    projectId: 'mailsender-3ca8b',
    storageBucket: 'mailsender-3ca8b.appspot.com',
    iosClientId: '731342575492-hc3ue2f6q3pqi12rio29oprjhma52su6.apps.googleusercontent.com',
    iosBundleId: 'com.example.peluqueria',
  );
}
